version: '3.7'

services:

  zookeeper:
    image: 'bitnami/zookeeper:3.6.3'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - kafka-network
    restart: unless-stopped

  kafka:
    image: 'bitnami/kafka:2.8.1'
    depends_on:
      - zookeeper
    environment:
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    networks:
      - kafka-network
    restart: unless-stopped

  bianance-stream:
    image: bianance-stream
    build:
      context: ./
    volumes:
      - type: bind
        source: ./examples/config.kafka.gin
        target: /config.gin
    environment:
      - BINANCE_STREAM_CONFIG=/config.gin
    networks:
      - kafka-network
    restart: unless-stopped

networks:

  kafka-network:
    external: false
    name: kafka-network